[workspace]

members = [
    "kernel",
    "bootloader/raspi",

    "libs/arch/raspi/peripherals",
    "libs/arch/raspi/concurrency",
    "libs/arch/raspi/memory",
    "libs/elf-parse",
]

[profile.release]
strip = true