[workspace]

members = [
    "kernel",
    "bootloader/raspi",

    "libs/arch/raspi/peripherals",
    "libs/arch/raspi/concurrency",
    "libs/arch/raspi/paging",
    "libs/page-frame-allocator",
    "libs/elf-parse",
]