[package]
name = "bootloader-raspi"
version = "0.1.0"
edition = "2021"

[dependencies]
raspi-concurrency = { path = "../../libs/arch/raspi/concurrency" }
raspi-peripherals = { path = "../../libs/arch/raspi/peripherals" }
